# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data
```{r ReadData}
  library(plyr)
  library(lattice)
  unzip("activity.zip")
  activity <- read.csv("activity.csv")
  activity$date <- as.Date(activity$date)
```


## What is mean total number of steps taken per day?
```{r MeanSteps}
  steps.mean.day <- ddply(activity, .(date), summarize, mean = mean(steps))
  histogram(~mean, steps.mean.day)
```


## What is the average daily activity pattern?
```{r DailyActivity}
  activity.clean <- activity[!is.na(activity$steps),]
  steps.mean.interval <- ddply(activity.clean, .(interval), summarize, mean = mean(steps))
  xyplot(mean~interval, data=steps.mean.interval, type="l")
  steps.mean.interval.max <- steps.mean.interval$interval[which.max(steps.mean.interval$mean)]
  steps.mean.interval.max
```


## Imputing missing values
```{r ImputeMissing}
  missing <- activity[is.na(activity$steps),]
  missing.count <- nrow(missing)
  missing.count
```


## Are there differences in activity patterns between weekdays and weekends?
